### ISSUE TITLE
Add Music Issue

### ISSUE THREAD

**Issue by Ajmal112** [fssa-batch3/durgalakshmi.perumal__web_project#16]
### Description of issue
when I try to add the music to this website , we can give any link or any words as input. 

### Expected result
the pattern input for link should be required. user should give proper input 

### Actual result
when user gives any input . it is added and the song is not played.

### Steps to reproduce
1. click the add books button - create new songs.
2. click the edit button in the book card and edit or change the details.
3. click the edit button in that, you can see the delete button click delete to delete the song.

```
Path:      /pages/musics.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--livre-book-store.netlify.app%2Fpages%2Fmusics.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--livre-book-store.netlify.app/pages/musics.html)

**Comment by Durgalaks** [comment]
``
